name = "xget"
main = "src/index.js"
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
